# Generated by Django 2.2.14 on 2020-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='icons')),
                ('active', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
