# Generated by Django 2.2.14 on 2020-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxfGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=1)),
                ('productimg', models.CharField(max_length=64)),
                ('productname', models.CharField(max_length=32)),
                ('productlongname', models.CharField(max_length=64)),
                ('isxf', models.BooleanField(default=False)),
                ('pmdesc', models.IntegerField(default=1)),
                ('specifics', models.CharField(max_length=32)),
                ('price', models.FloatField(default=1)),
                ('marketprice', models.FloatField(default=1)),
                ('categoryid', models.IntegerField(default=1)),
                ('childcid', models.IntegerField(default=1)),
                ('childcidname', models.CharField(max_length=64)),
                ('dealerid', models.IntegerField(default=1)),
                ('storenums', models.IntegerField(default=200)),
                ('productnum', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
